#!/bin/bash
#PBS -l walltime=12:00:00
#PBS -l select=1:ncpus=1:mem=1gb

module load anaconda3/personal

echo "R is about to run"

cp $HOME/MAIN.R $TMPDIR
cp $HOME/cluster_simulation.R $TMPDIR
R --vanilla <cluster_simulation.R

mv simulation_results* $HOME/output_files/neutral_cluster_output

echo "R has finished running"